name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env for CI
        run: |
          printf "CALCULATOR_LOG_DIR=logs\nCALCULATOR_HISTORY_DIR=history\nCALCULATOR_MAX_HISTORY_SIZE=100\nCALCULATOR_AUTO_SAVE=true\nCALCULATOR_DEFAULT_ENCODING=utf-8\n" > .env
      - name: Run tests
        run: pytest
